### Create a product
POST http://localhost:5000/api/auth/add-product
Content-Type: application/json

{
    "product_id": "F03-097-1610-722",
    "product_name": "Đàn Ukulele Soprano, Walnut FB, Natural",
    "product_description": "Mang nguồn cảm hứng từ ngoại hình thú vị và tinh thần vô tư, độc đáo của Venice, California, Fender đã sản xuất ukulele soprano bắt trọn cảm giác đó—Venice Ukulele. Nhờ thân đàn có kích thước nhỏ gọn, Venice có thể đi khắp mọi nơi nhưng vẫn giữ được âm thanh sáng, classic, là cây đàn cần có đối với người chơi đàn hiện nay.",
    "specifications": {
        "Màu Thân": "Natural",
        "Finish thân": "Satin",
        "Dây đàn": "Standard Soprano Uke",
        "Kiểu thân": "Soprano-sized",
        "Độ cong cần":"Flat",
        "Độ dài Scale": "13.6 inch (345 mm)",
        "Số phím": "12",
        "Inlays mặt cần": "Chấm tròn",
        "Bộ khóa": "Open-Back Geared",
        "Hardware Finish": "Chrome",
        "Gỗ thân đàn": "Laminated Basswood",
        "Bridge": "Laminated Hardwood",
        "Mặt cần": "Walnut"
    },
    "brand_id": "F03",
    "purchase_price": 2220000,
    "current_price": 2420000,
    "quantity_in_stock": 6,
    "list_product_categories": [
        "UKU",
        "HOT"
    ],
    "list_images": [
        "1MdiKw5eM-6AnfdPNcmVA-BAiGebHgt2Q",
        "190SVuZ8kAbxez2TOvstTYSk7FHRLkqJ8",
        "1t_tZ6HwOZa8uKi1JNU8P-JBHylXSQbr9",
        "1MD1ibd9etHsSHyZD12YzOenKj7J8t7hS",
        "1T3Mlecu-15qr26nFZHccFHN7Wzukqzne"
    ]
}