### Get all products
GET http://localhost:5000/api/auth/products

### Create a product
POST http://localhost:5000/api/auth/add-product
Content-Type: application/json

{
    "product_id": "J150",
    "product_name": "Đàn Guitar Acoustic",
    "product_description": "Đàn Guitar Acoustic Ba Đờn J150 là mẫu đàn thuộc phân khúc dành cho người mới bắt đầu của Ba Đờn. Đây là một model bán khá chạy của Ba đờn , với giá thành hợp lý đây là một trong những sự lựa chọn tốt dành cho người mới chơi.\nKiểu Dáng A Jumbo Khuyết :\nBa đờn J150 được thiết kế với dáng A khuyết thon gọn, giúp người chơi dễ ôm và cầm nắm khi tập luyện. Đây là dáng đàn phù hợp với những bạn có vóc dáng nhỏ, hoặc các bạn nữ có thể lựa chọn\n\nCấu Hình Full Gỗ Thịt:\nVới thông số mặt Top gỗ thông , lưng và hông đàn được làm bằng gỗ Hồng đào , toàn bộ đàn đều là gỗ nguyên tấm giúp tiếng đàn chắc chắn, có độ vang tốt. Ngoài ra action đàn cũng được căn chỉnh hợp lý dành cho người mới chơi, đây cũng là ưu điểm nổi bật của mẫu đàn này.",
    "specifications": "",
    "brand_id": "3BD",
    "purchasing_price": 1900000,
    "current_price": 1900000,
    "quantity_in_stock": 94,
}